using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace backend.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            var createProjectsTableSql = ActiveProvider switch
            {
                "Microsoft.EntityFrameworkCore.Sqlite" => "CREATE TABLE IF NOT EXISTS \"Projects\" (\"Id\" INTEGER NOT NULL CONSTRAINT \"PK_Projects\" PRIMARY KEY AUTOINCREMENT, \"Name\" TEXT NOT NULL)",
                "Npgsql.EntityFrameworkCore.PostgreSQL" => "CREATE TABLE IF NOT EXISTS \"Projects\" (\"Id\" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"Name\" text NOT NULL)",
                _ => throw new NotSupportedException($"The provider '{ActiveProvider}' is not supported by this migration.")
            };

            migrationBuilder.Sql(createProjectsTableSql);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Projects");
        }
    }
}
